### ISSUE TITLE
ISAC not calculating coverage for CSR which are getting updated only in trap handler

### ISSUE THREAD

**Issue by UmerShahidengr** [riscv-software-src/riscv-isac#58] opened 2022-10-18 14:02 UTC
Dear All,
I have written a basic test in which I am causing illegal instruction exception in M-mode. Here is the test.
[basic.txt](https://github.com/riscv-software-src/riscv-isac/files/9811168/basic.txt)
This exception will update mcause register and will display it in the signature (which is happening correctly). I have written the following coverpoints for this test.

mcause:
  config: 
    - check ISA:=regex(.*I.*Zicsr.*); def rvtest_mtrap_routine=True; def rvtest_strap_routine=True
  mnemonics: 
    csrrw: 0
    csrrs: 0
  csr_comb:
    mcause & 0x01 == 0x01 : 0
    mcause & 0x02 == 0 x02: 0
    mcause & 0x03 == 0x03 : 0

The coverpoint (mcause & 0x02 == 0x02 : 0) should have been passed due to the illegal instruction exception but ISAC is showing it in the report.

**Comment by pawks** [comment] 2023-04-09 20:53
I think my last comment should have explained the cause. The behavior you see is by design. Hence, closing the issue. Feel free to reopen if further problems arise.

**Closed by pawks** 2023-04-09 20:53 UTC
